### ISSUE TITLE
Make The Website Searchable

### ISSUE THREAD

**Issue by PZR2000** [PZR2000/crls-club-review#1]
Right now the search bar does nothing. We need to grab the string the user inputs and search through the js object to return clubs with words similar to the what the user is searching for.

**Comment by psvenk** [comment]
I'm not sure how many solutions there are that would not require a backend. One interesting one is [tinysearch](https://endler.dev/2019/tinysearch/) — this seems to be very fast (at least in part thanks to WebAssembly) for reasonably small websites yet running entirely in the browser

**Comment by PZR2000** [comment]
I just added some search functionality but it is a bit rudimentary, so we could definitely use a more complex system for better club searching.
